{
  "jobs": {
    "vm-fbsd": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v6.0.2"
        },
        {
          "run": "(git gc --quiet || :)"
        },
        {
          "uses": "vmactions/freebsd-vm@v1.4.2",
          "with": {
            "arch": "${{ matrix.arch }}",
            "copyback": false,
            "mem": 2048,
            "release": "${{ matrix.release }}",
            "run": "sh .extra/btnormal.sh",
            "sync": "scp",
            "usesh": true
          }
        }
      ],
      "strategy": {
        "matrix": {
          "arch": [
            "aarch64",
            "riscv64",
            "x86_64"
          ],
          "release": [
            "15.0",
            "14.3"
          ]
        }
      }
    }
  },
  "name": "vm-bsd-free",
  "on": {
    "push": {
      "branches": [
        "GHA"
      ]
    },
    "workflow_dispatch": null
  }
}
