{
  "jobs": {
    "vm-haiku": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v6.0.1"
        },
        {
          "run": "(git gc --quiet || :)"
        },
        {
          "uses": "vmactions/haiku-vm@v1.0.1",
          "with": {
            "copyback": false,
            "mem": 2048,
            "run": "sh .extra/vm-haiku.sh",
            "usesh": true
          }
        }
      ]
    }
  },
  "name": "vm-haiku",
  "on": {
    "push": {
      "branches": [
        "GHA"
      ]
    },
    "workflow_dispatch": null
  }
}
