{
  "jobs": {
    "vm-obsd": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v6.0.1"
        },
        {
          "run": "(git gc --quiet || :)"
        },
        {
          "uses": "vmactions/openbsd-vm@v1.3.1",
          "with": {
            "arch": "${{ matrix.arch }}",
            "copyback": false,
            "mem": 2048,
            "run": "sh .extra/btnormal.sh",
            "usesh": true
          }
        }
      ],
      "strategy": {
        "matrix": {
          "arch": [
            "aarch64",
            "riscv64",
            "x86_64"
          ]
        }
      }
    }
  },
  "name": "vm-obsd",
  "on": {
    "push": {
      "branches": [
        "GHA"
      ]
    },
    "workflow_dispatch": null
  }
}
