{
  "jobs": {
    "vm-slowlartus": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v6.0.2"
        },
        {
          "run": "(git gc --quiet || :)"
        },
        {
          "uses": "vmactions/solaris-vm@v1.3.0",
          "with": {
            "copyback": false,
            "mem": 4096,
            "release": "11.4-gcc",
            "run": "sh .extra/vm-slowlartus.sh",
            "usesh": true
          }
        }
      ]
    }
  },
  "name": "vm-sunos-solaris",
  "on": {
    "workflow_dispatch": null
  }
}
