{
  "jobs": {
    "vm-openindiana": {
      "runs-on": "ubuntu-latest",
      "steps": [
        {
          "uses": "actions/checkout@v6.0.2"
        },
        {
          "run": "(git gc --quiet || :)"
        },
        {
          "uses": "vmactions/openindiana-vm@v1.0.5",
          "with": {
            "copyback": false,
            "mem": 5120,
            "prepare": "pkg install build-essential",
            "run": "sh .extra/vm-slowlartus.sh",
            "usesh": true
          }
        }
      ]
    }
  },
  "name": "vm-sunos-indiana",
  "on": {
    "workflow_dispatch": null
  }
}
